const AUTH_TYPES = {
  RESET_STATE: "RESET_STATE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  LOGOUT: "LOGOUT",
  PARENT_CATEGORIES: "PARENT_CATEGORIES",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  PROFILE_SUCCESS: "PROFILE_SUCCESS",
  SET_CART: "SET_CART",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  GETNOTIFICATION: "GETNOTIFICATION",
  GETPRODUCTDETAILS: "GETPRODUCTDETAILS",
  GETORDERDETAILS: "GETORDERDETAILS",
};

export default AUTH_TYPES;
