const API_TOKEN = "API_TOKEN";
const SIGNUP_TOKEN = "SIGNUP_TOKEN";
const LOGOUT_TOKEN = "LOGOUT_TOKEN";
const CHECKOUT_TOKEN = "CHECKOUT_TOKEN";
const COUPON = "COUPON";
const VALIDITY_DATE = "VALIDITY_DATE";

export {
  API_TOKEN,
  SIGNUP_TOKEN,
  LOGOUT_TOKEN,
  CHECKOUT_TOKEN,
  COUPON,
  VALIDITY_DATE,
};
