#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_msg=$(cat "$1")

regex="^(feat|fix|docs|style|refactor|perf|test|chore)(\([A-Za-z0-9_\-]+\))?: .+$"


if ! [[ $commit_msg =~ $regex ]]; then
 echo "Invalid commit message format. Please use 'type (scope): description'"
 exit 1
fi
